### ISSUE TITLE
Feature Request: Add support for `cw-axe log --start <milliseconds_since_1970>` and `cw-axe log --start <seconds_since_1970>` formats

### ISSUE THREAD

**Issue by DeflateAwning** [mikhail-m1/axe#6]
Feature Request: Add support for `cw-axe log --start <milliseconds_since_1970>` and `cw-axe log --start <seconds_since_1970>` formats.

Use case: In a high-traffic web server, it's helpful to be able to view logs for a specific request. I'm adding an admin account HTTP response parameter that is a full cw-axe command to get that specific request. It'd be easier to include in that command timestamp in this format.

**Comment by mikhail-m1** [comment]
I added support for unit epoch timestamps, please let me know if something is not right.
